### ISSUE TITLE
What's the difference between this and excel micro?

### ISSUE THREAD

**Issue by dalexander01** [unional/typescript-guidelines#12]
https://github.com/excelmicro/typescript

**Comment by unional** [comment]
Thanks for the link. I wasn't aware of that.  

I'll check it out when I have a chance. 

It's probably has different opinion on things just as there are different style guides. 

My approach on this guideline is that it is not sufficient just taking about style without going in depth on why and how. 

You can checkout the introduction to see if that resonate with you. 

Another difference is that I work on typings, so this guideline includes that too.
