### ISSUE TITLE
Instead of tslint, suggest prettier

### ISSUE THREAD

**Issue by styfle** [unional/typescript-guidelines#21]
I see mention of [tslint](https://www.npmjs.com/package/tslint) but what about [prettier](https://www.npmjs.com/package/prettier) instead?

**Comment by unional** [comment]
Thanks for pointing it out. I have not used `prettier` myself, but it definitely worths taking a look at.

It also seems to work well with different IDEs.

PR is always welcome to add `prettier` configuration to the mix. 🌷

**Comment by styfle** [comment]
I just saw this repo so I haven't really looked through the configs and such. Not sure where to add it besides Linters section.

Here is a config from one of my projects: [.prettierrc.json](https://github.com/styfle/packagephobia/blob/master/.prettierrc.json)

And the here's the usage: [npm run prettier](https://github.com/styfle/packagephobia/blob/master/package.json#L9)

There is a [VS Code extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) if you want to use a keyboard shortcut to format your file.

**Comment by unional** [comment]
Will be adding `prettier` soon. :)
